# This rule is not used by the project mcr-scheme-headaches itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to example.mcr-scheme-headaches.ntnn.github.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mcr-scheme-headaches
    app.kubernetes.io/managed-by: kustomize
  name: source-viewer-role
rules:
- apiGroups:
  - example.mcr-scheme-headaches.ntnn.github.com
  resources:
  - sources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.mcr-scheme-headaches.ntnn.github.com
  resources:
  - sources/status
  verbs:
  - get
