# This rule is not used by the project mcr-scheme-headaches itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over example.mcr-scheme-headaches.ntnn.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mcr-scheme-headaches
    app.kubernetes.io/managed-by: kustomize
  name: source-admin-role
rules:
- apiGroups:
  - example.mcr-scheme-headaches.ntnn.github.com
  resources:
  - sources
  verbs:
  - '*'
- apiGroups:
  - example.mcr-scheme-headaches.ntnn.github.com
  resources:
  - sources/status
  verbs:
  - get
