# This rule is not used by the project mcr-scheme-headaches itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the example.mcr-scheme-headaches.ntnn.github.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mcr-scheme-headaches
    app.kubernetes.io/managed-by: kustomize
  name: target-editor-role
rules:
- apiGroups:
  - example.mcr-scheme-headaches.ntnn.github.com
  resources:
  - targets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.mcr-scheme-headaches.ntnn.github.com
  resources:
  - targets/status
  verbs:
  - get
