apiVersion: example.mcr-scheme-headaches.ntnn.github.com/v1alpha1
kind: Target
metadata:
  labels:
    app.kubernetes.io/name: mcr-scheme-headaches
    app.kubernetes.io/managed-by: kustomize
  name: target-sample
spec:
  # TODO(user): Add fields here
